#PBS -P q97
#PBS -q normal
#PBS -l walltime=18:00:00
#PBS -l mem=1100GB
#PBS -l jobfs=100GB
#PBS -l ncpus=384
#PBS -l software=underworld
#PBS -l wd
#PBS -lstorage=scratch/q97
#PBS -N Rift_20_008_noBls

source /scratch/q97/codes/UWGeodynamics_2.9.6.sh


MODELNAME="Rift_20_008_noBls"
OUTPUTPATH=`pwd`
SCRIPT="Rift_20_008_noBls.py"

# execution
mpiexec python3 ./$SCRIPT 1> $OUTPUTPATH/$MODELNAME.$PBS_JOBID.log 2> $OUTPUTPATH/$MODELNAME.$PBS_JOBID.err
