#PBS -P q97
#PBS -q normal
#PBS -l walltime=03:00:00
#PBS -l mem=1250GB
#PBS -l jobfs=100GB
#PBS -l ncpus=384
#PBS -l software=underworld
#PBS -l wd
#PBS -N CM_1_noBls_noSLvl
#PBS -l storage=scratch/q97

source /scratch/q97/codes/UWGeodynamics_2.9.6.sh

MODELNAME="CM_1_noBls_noSLvl"
OUTPUTPATH=`pwd`
SCRIPT="3_PMbis.py"

# execution
mpiexec python3 ./$SCRIPT 1> $OUTPUTPATH/$MODELNAME.$PBS_JOBID.log 2> $OUTPUTPATH/$MODELNAME.$PBS_JOBID.err
