#PBS -P q97
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l mem=1200GB
#PBS -l jobfs=100GB
#PBS -l ncpus=384
#PBS -l software=underworld
#PBS -l wd
#PBS -N CM_1_noBls_noSLvl
#PBS -l storage=gdata/m18

source /g/data/m18/codes/UWGeodynamics_2.10.sh

MODELNAME="CM_1_noBls_noSLvl"
OUTPUTPATH=`pwd`
SCRIPT="1_PM.py"

# execution
mpiexec python3 ./$SCRIPT 1> $OUTPUTPATH/$MODELNAME.$PBS_JOBID.log 2> $OUTPUTPATH/$MODELNAME.$PBS_JOBID.err
